version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Install and configure Selenium
          command: |
            pip install selenium
            # Cài đặt trình điều khiển trình duyệt (vd: Chrome)
            wget https://chromedriver.storage.googleapis.com/VERSION_NUMBER/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            mv chromedriver /usr/local/bin/
            # Cấu hình Selenium để sử dụng trình điều khiển trình duyệt
            export PATH=$PATH:/usr/local/bin/
      - run:
          name: Start Flask app
          command: |
            python app.py &
      - run:
          name: Run Selenium tests
          command: pytest tests/user-manage_test.py
          environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: apidashboarddb