version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.9
    environment:
      FLASK_APP: app.py
      FLASK_ENV: testing
      DATABASE_URL: postgresql://postgres:12345@localhost:5432/apidashboarddb
    working_directory: /testAPIProject
  selenium-executor:
    docker:
      - image: selenium/standalone-chrome
    working_directory: /testAPIProject

jobs:
  build:
    executor: python-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python -m unittest discover tests
  e2e:
    executor: selenium-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Start Flask app
          command: |
            python app.py &
      - run:
          name: Run Selenium tests
          command: |
            pytest